# Generated by Django 5.2.16 on 2026-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strName', models.CharField(max_length=200)),
                ('strDescription', models.TextField()),
                ('strTechStack', models.CharField(max_length=255)),
                ('strGithubUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('strLiveUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('boolIsFeatured', models.BooleanField(default=False)),
                ('strImageUrl', models.CharField(blank=True, max_length=500, null=True)),
                ('strKickerLabel', models.CharField(blank=True, max_length=150, null=True)),
                ('strCtaText', models.CharField(blank=True, max_length=100, null=True)),
                ('strCtaRoute', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'project_projectmodel',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strTitle', models.CharField(max_length=100)),
                ('strThemeColor', models.CharField(default='#4f46e5', max_length=50)),
                ('strThemeLight', models.CharField(default='rgba(79, 70, 229, 0.1)', max_length=50)),
                ('strIconSvg', models.TextField(blank=True, null=True)),
                ('strModalHtml', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portfolio_skillmodel',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strTitle', models.CharField(max_length=200)),
                ('strDescription', models.TextField(blank=True, null=True)),
                ('strYoutubeEmbedUrl', models.CharField(max_length=200)),
                ('boolIsFeatured', models.BooleanField(default=False)),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolio_videomodel',
            },
        ),
    ]
