# Generated by Django 5.2.16 on 2026-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strName', models.CharField(blank=True, max_length=150, null=True)),
                ('strDescription', models.TextField(blank=True, null=True)),
                ('numPrice', models.FloatField(blank=True, null=True)),
                ('strCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('strImage', models.CharField(blank=True, max_length=300, null=True)),
                ('boolInStock', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'merch_productmodel',
            },
        ),
    ]
