# Generated by Django 5.2.16 on 2026-08-13 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0002_rename_musing_post_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='jsonAnalysisParams',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='jsonAnalysisResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentauditcollectionmodel',
            name='collected_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentauditcollectionmodel',
            name='llm_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='blogcommentmodel',
            index=models.Index(fields=['user', 'strType', 'datePosted'], name='ix_comment_user_type_date'),
        ),
    ]
