# Generated by Django 5.2.16 on 2026-08-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUserModel',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password_reset_attempts',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password_reset_requested_at',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='strVerificationCode',
        ),
    ]
