import React from 'react';
import LegalPage from '../components/LegalPage';

const h2 = { fontSize: '1.1rem', color: '#f5f5f7', margin: '1.8rem 0 0.6rem' };
const p = { margin: '0 0 0.8rem' };

const TermsOfServicePage = () => (
  <LegalPage title="Terms of Service" updatedDate="July 5, 2026">
    <p style={p}>
      These terms govern your use of Synapse LE and its products, including VeriSphere. By
      creating an account or using this site, you agree to them.
    </p>

    <h2 style={h2}>Accounts</h2>
    <p style={p}>
      You're responsible for keeping your login credentials secure and for activity that
      happens under your account. You must provide accurate information at sign-up (an
      accurate email, at minimum, since it's used to verify and recover your account).
    </p>

    <h2 style={h2}>Acceptable use</h2>
    <p style={p}>
      Use of VeriSphere is additionally governed by the <a href="/verisphere/guidelines" style={{ color: '#8fb3ff' }}>Community Guidelines</a>.
      Beyond that, you agree not to use Synapse LE to break the law, to attack or disrupt the
      service itself (scraping at abusive volume, attempting to bypass rate limits or
      authentication, probing for vulnerabilities without authorization), or to impersonate
      another person or organization.
    </p>

    <h2 style={h2}>Content you post</h2>
    <p style={p}>
      You retain ownership of what you post. By posting it, you grant Synapse LE a license to
      display, store, and process it as needed to operate the service - including running it
      through the AI analysis features you or other users request.
    </p>

    <h2 style={h2}>AI analysis</h2>
    <p style={p}>
      Analysis results (fact-check summaries, fallacy detection, scoring) are generated by a
      third-party AI model and can be wrong. They're a tool to support judgment, not a
      substitute for it - see the Community Guidelines section on arguing in good faith.
    </p>

    <h2 style={h2}>Termination</h2>
    <p style={p}>
      We may suspend or terminate accounts that violate these terms or the Community
      Guidelines. You can deactivate your own account at any time from account settings.
    </p>

    <h2 style={h2}>Disclaimer and liability</h2>
    <p style={p}>
      Synapse LE is provided "as is," in active beta, without warranty of any kind. To the
      extent permitted by law, Synapse LE is not liable for damages arising from your use of
      the service, including reliance on AI-generated analysis.
    </p>

    <h2 style={h2}>Changes</h2>
    <p style={p}>
      These terms may be updated as the platform evolves. Continued use after a change means
      you accept the updated terms.
    </p>

    <h2 style={h2}>Contact</h2>
    <p style={p}>
      Questions about these terms: <a href="mailto:vsapofficial@gmail.com" style={{ color: '#8fb3ff' }}>vsapofficial@gmail.com</a>.
    </p>
  </LegalPage>
);

export default TermsOfServicePage;
