# Generated by Django 5.2.16 on 2026-08-13 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('posts', '0002_rename_musing_post_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogaianalysismodel',
            name='analysis_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogauditcollectionmodel',
            name='collected_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogauditcollectionmodel',
            name='comment_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogauditcollectionmodel',
            name='context_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogauditcollectionmodel',
            name='llm_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogauditcollectionmodel',
            name='source_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='jsonAllowedAnalysisFocus',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='blogmodel',
            index=models.Index(fields=['author', 'datePublished'], name='ix_blog_author_datepub'),
        ),
    ]
